#!/bin/bash

# install pre-requisites (Python packages)
pip install /tmp/cstbox-whl/*.whl

# schedules our analyze tasks if not yet here

crontab=/etc/cstbox/crontab

task_name="periodic-analytics"

schedule_day="0 12 * * *"        # at 12AM, every day (12AM used to work around the fact that WOOPA box is off at night)
schedule_week="0 12 * * 1"       # at 12AM, on Mondays
schedule_month="0 12 1 * *"      # at 12AM, on the 1st day of the month

for period in day week month; do
    comment="PERFORMER $task_name-$period"
    if ! grep -csq "$comment" $crontab ; then
        schedule_name="schedule_$period"
        schedule=${!schedule_name}
        user="root"
        command="python /opt/cstbox/bin/$task_name.py -p $period --config /etc/cstbox/analytics-$period.cfg"
        logfile="/var/log/cstbox/$task_name-$period.log"

        echo "$schedule $user $command >> $logfile 2>&1 # $comment" >> $crontab
    fi
done